//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.HistoryManagement {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.HistoryManagement.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录管理.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 筛选.
        /// </summary>
        public static string S_Filter {
            get {
                return ResourceManager.GetString("S_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认班级筛选.
        /// </summary>
        public static string S_Filter_SelectedClassName {
            get {
                return ResourceManager.GetString("S_Filter_SelectedClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 进入历史页时默认选择的班级。.
        /// </summary>
        public static string S_Filter_SelectedClassName_D {
            get {
                return ResourceManager.GetString("S_Filter_SelectedClassName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认奖池筛选.
        /// </summary>
        public static string S_Filter_SelectedPoolName {
            get {
                return ResourceManager.GetString("S_Filter_SelectedPoolName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 进入历史页时默认选择的奖池。.
        /// </summary>
        public static string S_Filter_SelectedPoolName_D {
            get {
                return ResourceManager.GetString("S_Filter_SelectedPoolName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string S_History {
            get {
                return ResourceManager.GetString("S_History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示权重信息.
        /// </summary>
        public static string S_History_SelectWeight {
            get {
                return ResourceManager.GetString("S_History_SelectWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看历史记录时显示参与抽取的权重信息。.
        /// </summary>
        public static string S_History_SelectWeight_D {
            get {
                return ResourceManager.GetString("S_History_SelectWeight_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示抽奖历史.
        /// </summary>
        public static string S_History_ShowLottery {
            get {
                return ResourceManager.GetString("S_History_ShowLottery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在历史页中显示抽奖记录。.
        /// </summary>
        public static string S_History_ShowLottery_D {
            get {
                return ResourceManager.GetString("S_History_ShowLottery_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示点名历史.
        /// </summary>
        public static string S_History_ShowRollCall {
            get {
                return ResourceManager.GetString("S_History_ShowRollCall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在历史页中显示点名记录。.
        /// </summary>
        public static string S_History_ShowRollCall_D {
            get {
                return ResourceManager.GetString("S_History_ShowRollCall_D", resourceCulture);
            }
        }

        public static string S_ClearHistory {
            get {
                return ResourceManager.GetString("S_ClearHistory", resourceCulture);
            }
        }

        public static string S_ClearHistory_RollCall {
            get {
                return ResourceManager.GetString("S_ClearHistory_RollCall", resourceCulture);
            }
        }

        public static string S_ClearHistory_RollCall_D {
            get {
                return ResourceManager.GetString("S_ClearHistory_RollCall_D", resourceCulture);
            }
        }

        public static string S_ClearHistory_Lottery {
            get {
                return ResourceManager.GetString("S_ClearHistory_Lottery", resourceCulture);
            }
        }

        public static string S_ClearHistory_Lottery_D {
            get {
                return ResourceManager.GetString("S_ClearHistory_Lottery_D", resourceCulture);
            }
        }

        public static string C_Clear {
            get {
                return ResourceManager.GetString("C_Clear", resourceCulture);
            }
        }

        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        public static string M_ClearConfirm_Title {
            get {
                return ResourceManager.GetString("M_ClearConfirm_Title", resourceCulture);
            }
        }

        public static string M_ClearConfirm_Content {
            get {
                return ResourceManager.GetString("M_ClearConfirm_Content", resourceCulture);
            }
        }

        public static string M_ClearSuccess {
            get {
                return ResourceManager.GetString("M_ClearSuccess", resourceCulture);
            }
        }

        public static string M_ClearFailed {
            get {
                return ResourceManager.GetString("M_ClearFailed", resourceCulture);
            }
        }

        public static string M_SelectFirst {
            get {
                return ResourceManager.GetString("M_SelectFirst", resourceCulture);
            }
        }

        public static string S_ExportHistory {
            get {
                return ResourceManager.GetString("S_ExportHistory", resourceCulture);
            }
        }

        public static string S_ExportHistory_RollCall {
            get {
                return ResourceManager.GetString("S_ExportHistory_RollCall", resourceCulture);
            }
        }

        public static string S_ExportHistory_RollCall_D {
            get {
                return ResourceManager.GetString("S_ExportHistory_RollCall_D", resourceCulture);
            }
        }

        public static string S_ExportHistory_Lottery {
            get {
                return ResourceManager.GetString("S_ExportHistory_Lottery", resourceCulture);
            }
        }

        public static string S_ExportHistory_Lottery_D {
            get {
                return ResourceManager.GetString("S_ExportHistory_Lottery_D", resourceCulture);
            }
        }

        public static string C_Export {
            get {
                return ResourceManager.GetString("C_Export", resourceCulture);
            }
        }

        public static string C_ExportRollCallName {
            get {
                return ResourceManager.GetString("C_ExportRollCallName", resourceCulture);
            }
        }

        public static string C_ExportLotteryName {
            get {
                return ResourceManager.GetString("C_ExportLotteryName", resourceCulture);
            }
        }

        public static string O_AllLists {
            get {
                return ResourceManager.GetString("O_AllLists", resourceCulture);
            }
        }

        public static string O_AllPools {
            get {
                return ResourceManager.GetString("O_AllPools", resourceCulture);
            }
        }

        public static string M_SelectExportFirst {
            get {
                return ResourceManager.GetString("M_SelectExportFirst", resourceCulture);
            }
        }

        public static string M_ExportSuccess {
            get {
                return ResourceManager.GetString("M_ExportSuccess", resourceCulture);
            }
        }

        public static string M_ExportFailed {
            get {
                return ResourceManager.GetString("M_ExportFailed", resourceCulture);
            }
        }

        public static string M_NoHistoryToExport {
            get {
                return ResourceManager.GetString("M_NoHistoryToExport", resourceCulture);
            }
        }

        public static string E_ProfileRollCall {
            get {
                return ResourceManager.GetString("E_ProfileRollCall", resourceCulture);
            }
        }

        public static string E_ProfileLottery {
            get {
                return ResourceManager.GetString("E_ProfileLottery", resourceCulture);
            }
        }

        public static string E_DrawTime {
            get {
                return ResourceManager.GetString("E_DrawTime", resourceCulture);
            }
        }

        public static string E_RecordNumber {
            get {
                return ResourceManager.GetString("E_RecordNumber", resourceCulture);
            }
        }

        public static string E_RecordName {
            get {
                return ResourceManager.GetString("E_RecordName", resourceCulture);
            }
        }

        public static string E_Gender {
            get {
                return ResourceManager.GetString("E_Gender", resourceCulture);
            }
        }

        public static string E_Group {
            get {
                return ResourceManager.GetString("E_Group", resourceCulture);
            }
        }

        public static string E_DrawMethod {
            get {
                return ResourceManager.GetString("E_DrawMethod", resourceCulture);
            }
        }

        public static string E_DrawCount {
            get {
                return ResourceManager.GetString("E_DrawCount", resourceCulture);
            }
        }

        public static string E_DrawGender {
            get {
                return ResourceManager.GetString("E_DrawGender", resourceCulture);
            }
        }

        public static string E_DrawGroup {
            get {
                return ResourceManager.GetString("E_DrawGroup", resourceCulture);
            }
        }

        public static string E_Subject {
            get {
                return ResourceManager.GetString("E_Subject", resourceCulture);
            }
        }

        public static string E_Weight {
            get {
                return ResourceManager.GetString("E_Weight", resourceCulture);
            }
        }

        public static string E_TotalCount {
            get {
                return ResourceManager.GetString("E_TotalCount", resourceCulture);
            }
        }

        public static string E_LastDrawTime {
            get {
                return ResourceManager.GetString("E_LastDrawTime", resourceCulture);
            }
        }

        public static string E_MethodRandom {
            get {
                return ResourceManager.GetString("E_MethodRandom", resourceCulture);
            }
        }

        public static string E_MethodWeight {
            get {
                return ResourceManager.GetString("E_MethodWeight", resourceCulture);
            }
        }

        public static string E_AllGenders {
            get {
                return ResourceManager.GetString("E_AllGenders", resourceCulture);
            }
        }

        public static string E_AllGroups {
            get {
                return ResourceManager.GetString("E_AllGroups", resourceCulture);
            }
        }

        public static string E_BreakSubject {
            get {
                return ResourceManager.GetString("E_BreakSubject", resourceCulture);
            }
        }

        public static string E_SheetRollCallRecords {
            get {
                return ResourceManager.GetString("E_SheetRollCallRecords", resourceCulture);
            }
        }

        public static string E_SheetRollCallSummary {
            get {
                return ResourceManager.GetString("E_SheetRollCallSummary", resourceCulture);
            }
        }

        public static string E_SheetLotteryRecords {
            get {
                return ResourceManager.GetString("E_SheetLotteryRecords", resourceCulture);
            }
        }

        public static string E_SheetLotterySummary {
            get {
                return ResourceManager.GetString("E_SheetLotterySummary", resourceCulture);
            }
        }

        public static string C_ExportProfiles {
            get {
                return ResourceManager.GetString("C_ExportProfiles", resourceCulture);
            }
        }

        public static string C_ExportSubject {
            get {
                return ResourceManager.GetString("C_ExportSubject", resourceCulture);
            }
        }

        public static string C_ExportTimeRange {
            get {
                return ResourceManager.GetString("C_ExportTimeRange", resourceCulture);
            }
        }

        public static string C_ExportStartDate {
            get {
                return ResourceManager.GetString("C_ExportStartDate", resourceCulture);
            }
        }

        public static string C_ExportEndDate {
            get {
                return ResourceManager.GetString("C_ExportEndDate", resourceCulture);
            }
        }

        public static string C_ExportSort {
            get {
                return ResourceManager.GetString("C_ExportSort", resourceCulture);
            }
        }

        public static string C_ExportFormat {
            get {
                return ResourceManager.GetString("C_ExportFormat", resourceCulture);
            }
        }

        public static string O_AllSubjects {
            get {
                return ResourceManager.GetString("O_AllSubjects", resourceCulture);
            }
        }

        public static string O_TimeAll {
            get {
                return ResourceManager.GetString("O_TimeAll", resourceCulture);
            }
        }

        public static string O_TimeLast7Days {
            get {
                return ResourceManager.GetString("O_TimeLast7Days", resourceCulture);
            }
        }

        public static string O_TimeLast30Days {
            get {
                return ResourceManager.GetString("O_TimeLast30Days", resourceCulture);
            }
        }

        public static string O_TimeCustom {
            get {
                return ResourceManager.GetString("O_TimeCustom", resourceCulture);
            }
        }

        public static string O_SortTimeDesc {
            get {
                return ResourceManager.GetString("O_SortTimeDesc", resourceCulture);
            }
        }

        public static string O_SortTimeAsc {
            get {
                return ResourceManager.GetString("O_SortTimeAsc", resourceCulture);
            }
        }

        public static string O_FormatXlsx {
            get {
                return ResourceManager.GetString("O_FormatXlsx", resourceCulture);
            }
        }

        public static string O_FormatCsv {
            get {
                return ResourceManager.GetString("O_FormatCsv", resourceCulture);
            }
        }

        public static string M_SelectExportProfiles {
            get {
                return ResourceManager.GetString("M_SelectExportProfiles", resourceCulture);
            }
        }

        public static string M_ExportInvalidRange {
            get {
                return ResourceManager.GetString("M_ExportInvalidRange", resourceCulture);
            }
        }
    }
}
